server:
  port: 8033

# slf4j日志配置
logging:
  # 配置级别
  level:
    #分包配置级别，即不同的目录下可以使用不同的级别  error、warn、info、debug、trace、all
    root: info
  file:
    name: logfile/sys-web.log


# 文件存储路径
file:
  fileAbsolutePath:  F:/IT/file-server/file/
  picAbsolutePath: F:/IT/file-server/pic/
  fileRelativePath: /file
  picRelativePath: /pic
  # 文件大小 /M
  maxSize: 100
  picMaxSize: 10


spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB